### PR TITLE
support comma separated string as if it were a string slice

### PR DESCRIPTION
**Pull request by danbrakeley**
I wanted to use a list of strings for a config param, but I wanted to be able to get that list from an environment variable.

My solution is to modify GetStringSlice so that if it doesn't find a slice, it will then see if it has a string instead. If so, it splits that string on any commas, creating a []string.

### CODE REVIEW

**Comment by fzerorubigd** [comment]
Sorry for delay :) 
I like the idea, but could you please add a test for this in test too? thank you.

**Comment by danbrakeley** [comment]
Definitely, I'll try to get to that tonight.

**Comment by danbrakeley** [comment]
Done. Also updated the README's GetStringSlice() entry.

**Comment by danbrakeley** [comment]
Is there anything else I can do to help with this?

**Comment by fzerorubigd** [comment]
Thanks. squashed and merged into v2

**Pull request closed without merging**
